defaults: &defaults
  websocket_rails:
    standalone: false
    url: localhost
    port: 3000
    redis:
      host: localhost
      port: 6379
      db: 0

development:
  <<: *defaults

test:
  <<: *defaults

production:
  websocket_rails:
    standalone: false
    url: chatravel.herokuapp.com/websocket
    port: listen(process.env.PORT || 5000)
    redis:
      host: localhost
      port: 6379
      db: 0
